services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: client-container
    volumes:
      - ./client:/app
    restart: always
    networks:
      - assignment-network
    depends_on:
      - server

  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: server-container
    volumes:
      - ./server:/app
    restart: always
    networks:
      - assignment-network
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-container
    volumes:
      - mongoData:/data/db
    restart: always
    networks:
      - assignment-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=products
networks:
  assignment-network:
volumes:
  mongoData:
